### PR TITLE
Stream data in form of SSE

### LINKED ISSUE #9: Add support for streams.
Add support for giving a readable stream to the Session to pipe the stream data to the client via separate SSE events or individual `data` fields one after another as part of the same event.

One consideration here might be that this behaviour would be difficult to combine with the `Session#data` method as the user may want to know when the stream has finished piping, and thus returning something like a [promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) to indicate that it is done would mean that the method would no longer return the `Session` instance and would not be chainable with other methods anymore.

Alternatively, a completely separate method could be added (eg, `Session#stream`) that takes in only a stream and returns a promise to indicate when the stream has finished completing, though this also would not be chainable with other methods.

### PR DESCRIPTION
**Pull request by abhi12299**
Add enhancement for streaming data as server sent events. This adds a new method on the Session abstract class to stream data.
Added example usage in readme.
The stream function returns a promise with a boolean value indicating whether the streaming was finished or not. It can reject in case of any error.

Resolves #9

### CODE REVIEW

**Review by MatthewWid — CHANGES_REQUESTED** [review]
I think for the examples should be separated into 'getting-started' and 'streams' as they're demonstrating two different things (even just copy the current 'getting-started' in your fork into a new 'streams' folder and restore the original); as well as keeping the README minimal and letting the docs do the rest of the work.

Other than that the code itself looks great, thanks!

**Comment by abhi12299** [comment]
All requested changes are done.

**Review by MatthewWid — APPROVED** [review]
Looks good, thanks so much for contributing!

**Comment by abhi12299** [comment]
There's an issue with the streams example. You forgot to change the stream event name on the client (in `public/index.js`) which defaults to `stream`, since you did not specify `sseEvent` in `res.stream` in `examples/streams/server.ts`

**Comment by MatthewWid** [comment]
Thanks for spotting this. Fixed.

**Pull request merged**
